### ISSUE TITLE
Is there a Node.js module for hunspell-bo ?

### ISSUE THREAD

**Issue by kmsheng** [eroux/hunspell-bo#1]
Hello, eroux !

Would you give me some clues about how to apply the spell check to my project ?
Thanks !
https://github.com/karmapa/ketaka-lite

**Comment by eroux** [comment]
Hello @kmsheng

These are just hunspell files, so you have to first integrate hunspell. There are some bindings [here](https://github.com/mscdex/spellcheck), [here](https://github.com/nathanjsweet/nodehun), [here](https://github.com/atom/node-spellchecker) and in other places as well... Note that Chromium (in which I believe ketaka-lite executes) already has hunspell bindings, it might be possible to install hunspell-bo, and make chromium use it, that's certainly the first thing I'd explore...

Let's keep in touch about that, tell me if you have trouble with the integration.

Thank you,

**Comment by kmsheng** [comment]
@eroux Thanks, I will reopen this issue if I have trouble

**Comment by kmsheng** [comment]
@eroux I've tried all of them, but they only provide checking for single word.
What I want was a function to check a whole paragraph and tells me which indices of words are incorrect so I can highlight them.

**Comment by eroux** [comment]
[This one](https://www.npmjs.com/package/nodehun-sentences) seems to do what you want (the hunspell library does sentence check, that's the way it's used by LibreOffice). But these are all results from [here](https://www.google.fr/?gfe_rd=cr&ei=Y-UpVp6OOMXI8gf-o7zoBQ&gws_rd=cr#q=node+hunspell), I have genuinely no experience in node bindings for hunspell... Did you explore the option of a chrome extension? There seems to be many around using hunspell, but I don't know if it can be integrated into ketaka.

**Comment by kmsheng** [comment]
@eroux Thanks for replying, I will try that one : )

**Comment by kmsheng** [comment]
@eroux are you able to make this repo a npm module? so i can install this by npm install and take benefit of its package / version management. otherwise I have to track your files in my git repo or making it a git submodule.

**Comment by eroux** [comment]
I admit I would prefer a git submodule than packaging it for Node, as it could also be packaged for Ruby, Python, Lua, Rust, Go, Perl, etc. and I'm not sure I want to maintain that...

**Comment by kmsheng** [comment]
Ok, no problem : )
